services:
  otterwiki:
    image: redimp/otterwiki:2.15
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 8070:80
    volumes:
      - $DOCKER_VOLUMES/otterwiki/app-data:/app-data
