services:
  dokuwiki:
    image: dokuwiki/dokuwiki:stable
    ports:
      - "8100:8080"
    user: "1000:1000"
    environment:
      - PHP_UPLOADLIMIT=128M
      - PHP_MEMORYLIMIT=256M
      - PHP_TIMEZONE=UTC
    volumes:
      - $HOME/dockercompose/dokuwiki:/storage
